language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shrader/docker-react -f Dockerfile.dev .

script:
  - docker run shrader/docker-react npm run test -- --coverage
